{
 "title": "DevSecOps Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Sprint",
    "query": "Sprint 1 : 2023-08-28 00:00:00.000 - 2023-09-15 23:59:59.999 , Sprint 2 : 2023-09-16 00:00:00.000 - 2023-09-29 23:59:59.999 , Sprint 3 : 2023-09-30 00:00:00.000 - 2023-10-16 23:59:59.999 , Sprint 4 : 2023-10-17 00:00:00.000 - 2023-10-27 23:59:59.999 , Sprint 5 : 2023-10-28 00:00:00.000 - 2023-11-12 23:59:59.999 , Sprint 6 : 2023-11-13 00:00:00.000 - 2023-11-23 23:59:59.999 , Sprint 7 : 2023-11-24 00:00:00.000 - 2023-12-06 23:59:59.999 , Sprint 8 : 2023-12-05 00:00:00.000 - 2023-12-22 23:59:59.999 , Sprint 9 : 2023-12-18 00:00:00.000 - 2024-01-02 23:59:59.999"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment Frequency",
   "type": "barchart",
   "description": "Number of Jenkins pipeline builds executed for microservices deployment",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  sd.time1,\n  COALESCE(cd.successful_build_count, 0) as successful_build_count,\n  COALESCE(cd.failed_build_count, 0) as failed_build_count\nFROM (\n  SELECT 'Sprint 10' as time1\n  UNION\n  SELECT 'Sprint 11' as time1\n  UNION\n  SELECT 'Sprint 12' as time1 -- Corrected alias to match with 'Sprint 10'\n) AS sd\nLEFT JOIN (\n  SELECT\n    time1,\n    count(distinct case when result = 'SUCCESS' then id else null end) as successful_build_count,\n    count(distinct case when result != 'SUCCESS' then id else null end) as failed_build_count\n  FROM (\n    SELECT\n      'Sprint 10' as time1,\n      id,\n      result\n    FROM cicd_pipelines\n    WHERE\n      id LIKE \"%jenkins%\" AND\n      finished_date >= '2024-01-08 00:00:00.000' AND\n      finished_date <= '2024-02-05 23:59:59.999'\n  \n    UNION ALL\n  \n    SELECT\n      'Sprint 11' as time1,\n      id,\n      result\n    FROM cicd_pipelines\n    WHERE\n      id LIKE \"%jenkins%\" AND\n      finished_date >= '2024-02-19 00:00:00.000' AND\n      finished_date <= '2024-03-01 23:59:59.999'\n\n    UNION ALL\n\n    SELECT\n      'Sprint 12' as time1,\n      id,\n      result\n    FROM cicd_pipelines\n    WHERE\n      id LIKE \"%jenkins%\" AND\n      finished_date >= '2024-03-04 00:00:00.000' AND\n      finished_date <= '2024-03-15 23:59:59.999'\n  ) AS subquery\n  GROUP BY time1\n) AS cd ON sd.time1 = cd.time1;\n\n"
    }
   ]
  },
  {
   "title": "Change Volume",
   "type": "barchart",
   "description": "Number of lines of code changed",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sd.time1,\n  COALESCE(cd.lines_of_code_changed, 0) as lines_of_code_changed\nFROM (\n  SELECT 'Sprint 10' as time1\n  UNION\n  SELECT 'Sprint 11' as time1\n  UNION\n  SELECT 'Sprint 12' as time1\n) AS sd\nLEFT JOIN (\n  SELECT\n    time1,\n    SUM(additions) - SUM(deletions) as lines_of_code_changed\n  FROM (\n    SELECT\n      'Sprint 10' as time1,\n      additions,\n      deletions\n    FROM commits\n    WHERE\n      committed_date >= '2024-01-08 00:00:00.000' AND\n      committed_date <= '2024-02-05 23:59:59.999'\n  \n    UNION ALL\n  \n    SELECT\n      'Sprint 11' as time1,\n      additions,\n      deletions\n    FROM commits\n    WHERE\n      committed_date >= '2024-02-19 00:00:00.000' AND\n      committed_date <= '2024-03-01 23:59:59.999'\n\n    UNION ALL\n\n    SELECT\n      'Sprint 12' as time1,\n      additions,\n      deletions\n    FROM commits\n    WHERE\n      committed_date >= '2024-03-04 00:00:00.000' AND\n      committed_date <= '2024-03-15 23:59:59.999'\n  ) AS subquery\n  GROUP BY time1\n) AS cd ON sd.time1 = cd.time1 OR (sd.time1 IS NULL AND cd.time1 IS NULL);\n"
    }
   ]
  },
  {
   "title": "Ticket Volume",
   "type": "barchart",
   "description": "Number of bugs raised",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  sd.time1,\n  COALESCE(cd.number_of_issues, 0) as number_of_issues\nFROM (\n  SELECT 'Sprint 10' as time1\n  UNION\n  SELECT 'Sprint 11' as time1\n  UNION\n  SELECT 'Sprint 12' as time1\n) AS sd\nLEFT JOIN (\n  SELECT\n    time1,\n    count(*) as number_of_issues\n  FROM (\n    SELECT\n      'Sprint 10' as time1\n    FROM issues\n    WHERE\n      created_date >= '2024-01-08 00:00:00.000' AND\n      created_date <= '2024-02-05 23:59:59.999' AND\n      type = \"BUG\"\n\n    UNION ALL\n\n    SELECT\n      'Sprint 11' as time1\n    FROM issues\n    WHERE\n      created_date >= '2024-02-19 00:00:00.000' AND\n      created_date <= '2024-03-01 23:59:59.999' AND\n      type = \"BUG\"\n\n    UNION ALL\n\n    SELECT\n      'Sprint 12' as time1\n    FROM issues\n    WHERE\n      created_date >= '2024-03-04 00:00:00.000' AND\n      created_date <= '2024-03-15 23:59:59.999' AND\n      type = \"BUG\"\n  ) AS subquery\n  GROUP BY time1\n) AS cd ON sd.time1 = cd.time1 OR (sd.time1 IS NULL AND cd.time1 IS NULL);\n"
    }
   ]
  },
  {
   "title": "Mean Time to Recovery",
   "type": "barchart",
   "description": "Average time taken to resolve bugs",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sd.time1,\n  COALESCE(cd.mean_time_to_recover_in_min, 0) as mean_time_to_recover_in_min\nFROM (\n  SELECT 'Sprint 10' as time1\n  UNION\n  SELECT 'Sprint 11' as time1\n  UNION\n  SELECT 'Sprint 12' as time1\n) AS sd\nLEFT JOIN (\n  SELECT\n    time1,\n    AVG(TIMESTAMPDIFF(MINUTE, created_date, resolution_date)) / 60 AS mean_time_to_recover_in_min\n  FROM (\n    SELECT\n      'Sprint 10' as time1,\n      created_date,\n      resolution_date\n    FROM issues\n    WHERE\n      created_date >= '2024-01-08 00:00:00.000' AND\n      created_date <= '2024-02-05 23:59:59.999'\n\n    UNION ALL\n\n    SELECT\n      'Sprint 11' as time1,\n      created_date,\n      resolution_date\n    FROM issues\n    WHERE\n      created_date >= '2024-02-19 00:00:00.000' AND\n      created_date <= '2024-03-01 23:59:59.999' AND\n      type =\"BUG\"\n\n    UNION ALL\n\n    SELECT\n      'Sprint 12' as time1,\n      created_date,\n      resolution_date\n    FROM issues\n    WHERE\n      created_date >= '2024-03-04 00:00:00.000' AND\n      created_date <= '2024-03-15 23:59:59.999' AND\n      type = \"BUG\"\n  ) AS subquery\n  GROUP BY time1\n) AS cd ON sd.time1 = cd.time1 OR (sd.time1 IS NULL AND cd.time1 IS NULL);\n"
    }
   ]
  },
  {
   "title": "Requirement vs Bug Effort",
   "type": "barchart",
   "description": "Time Spent on Development and Bug Fixing",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  sd.time1,\n  COALESCE(cd_bug.total_hours, 0) as total_hours_bug,\n  COALESCE(cd_requirement.total_hours, 0) as total_hours_requirement\n  -- CASE\n  --   WHEN COALESCE(cd_bug.total_hours, 0) + COALESCE(cd_requirement.total_hours, 0) = 0 THEN 0\n  --   ELSE ROUND((COALESCE(cd_bug.total_hours, 0) / (COALESCE(cd_bug.total_hours, 0) + COALESCE(cd_requirement.total_hours, 0))) * 100, 2)\n  -- END as percentage_bug,\n  -- CASE\n  --   WHEN COALESCE(cd_bug.total_hours, 0) + COALESCE(cd_requirement.total_hours, 0) = 0 THEN 0\n  --   ELSE ROUND((COALESCE(cd_requirement.total_hours, 0) / (COALESCE(cd_bug.total_hours, 0) + COALESCE(cd_requirement.total_hours, 0))) * 100, 2)\n  -- END as percentage_requirement\n\nFROM (\n  SELECT 'Sprint 10' as time1\n  UNION\n  SELECT 'Sprint 11' as time1\n  UNION\n  SELECT 'Sprint 12' as time1\n) AS sd\nLEFT JOIN (\n  SELECT\n    time1,\n    COALESCE(ROUND(SUM(TIMESTAMPDIFF(HOUR, created_date, updated_date)), 2), 0) as total_hours\n  FROM (\n    SELECT\n      'Sprint 10' as time1,\n      created_date,\n      updated_date\n    FROM issues\n    WHERE\n      created_date >= '2024-01-08 00:00:00.000' AND\n      created_date <= '2024-02-05 23:59:59.999' AND status = 'DONE' AND type = 'BUG'\n\n    UNION ALL\n\n    SELECT\n      'Sprint 11' as time1,\n      created_date,\n      updated_date\n    FROM issues\n    WHERE\n      created_date >= '2024-02-07 00:00:00.000' AND\n      created_date <= '2024-03-01 23:59:59.999' AND status = 'DONE' AND type = 'BUG'\n\n    UNION ALL\n\n    SELECT\n      'Sprint 12' as time1,\n      created_date,\n      updated_date\n    FROM issues\n    WHERE\n      created_date >= '2024-03-04 00:00:00.000' AND\n      created_date <= '2024-03-15 23:59:59.999' AND status = 'DONE' AND type = 'BUG'\n  ) AS subquery\n  GROUP BY time1\n) AS cd_bug ON sd.time1 = cd_bug.time1 OR (sd.time1 IS NULL AND cd_bug.time1 IS NULL)\nLEFT JOIN (\n  SELECT\n    time1,\n    COALESCE(ROUND(SUM(TIMESTAMPDIFF(HOUR, created_date, updated_date)), 2), 0) as total_hours\n  FROM (\n    SELECT\n      'Sprint 10' as time1,\n      created_date,\n      updated_date\n    FROM issues\n    WHERE\n      created_date >= '2024-01-08 00:00:00.000' AND\n      created_date <= '2024-02-05 23:59:59.999' AND status = 'DONE' AND type = 'REQUIREMENT'\n\n    UNION ALL\n\n    SELECT\n      'Sprint 11' as time1,\n      created_date,\n      updated_date\n    FROM issues\n    WHERE\n      created_date >= '2024-02-29 00:00:00.000' AND\n      created_date <= '2024-03-01 23:59:59.999' AND status = 'DONE' AND type = 'REQUIREMENT'\n\n    UNION ALL\n\n    SELECT\n      'Sprint 12' as time1,\n      created_date,\n      updated_date\n    FROM issues\n    WHERE\n      created_date >= '2024-03-04 00:00:00.000' AND\n      created_date <= '2024-03-15 23:59:59.999' AND status = 'DONE' AND type = 'REQUIREMENT'\n  ) AS subquery\n  GROUP BY time1\n) AS cd_requirement ON sd.time1 = cd_requirement.time1 OR (sd.time1 IS NULL AND cd_requirement.time1 IS NULL);"
    }
   ]
  },
  {
   "title": "Lead Time (Dev to Deploy)",
   "type": "barchart",
   "description": "Average time to taken to complete user stories",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "SELECT\n  sd.time1,\n  COALESCE(cd.total_hours, 0) as total_hours\nFROM (\n  SELECT 'Sprint 10' as time1\n  UNION\n  SELECT 'Sprint 11' as time1\n  UNION\n  SELECT 'Sprint 12' as time1\n) AS sd\nLEFT JOIN (\n  SELECT\n    time1,\n    ROUND(AVG(TIMESTAMPDIFF(HOUR, created_date, updated_date)), 2) as total_hours\n  FROM (\n    SELECT\n      'Sprint 10' as time1,\n      created_date,\n      updated_date\n    FROM issues\n    WHERE\n      created_date >= '2024-01-08 00:00:00.000' AND\n      created_date <= '2024-02-05 23:59:59.999' AND \n      status = 'DONE' AND\n      type = \"REQUIREMENT\"\n\n    UNION ALL\n\n    SELECT\n      'Sprint 11' as time1,\n      created_date,\n      updated_date\n    FROM issues\n    WHERE\n      created_date >= '2024-02-19 00:00:00.000' AND\n      created_date <= '2024-03-01 23:59:59.999' AND \n      status = 'DONE' AND\n      type = \"REQUIREMENT\"\n\n    UNION ALL\n\n    SELECT\n      'Sprint 12' as time1,\n      created_date,\n      updated_date\n    FROM issues\n    WHERE\n      created_date >= '2024-03-04 00:00:00.000' AND\n      created_date <= '2024-03-15 23:59:59.999' AND \n      status = 'DONE' AND\n      type = \"REQUIREMENT\"\n  ) AS subquery\n  GROUP BY time1\n) AS cd ON sd.time1 = cd.time1 OR (sd.time1 IS NULL AND cd.time1 IS NULL);\n"
    }
   ]
  },
  {
   "title": "Performance (Response Time)",
   "type": "piechart",
   "description": "Response time of each microservice",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "select * from jaeger;" }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "description": "Percentage of the cluster available",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - sum(kube_node_spec_unschedulable{node=~\".*\"}) / sum(kube_node_info{node=~\".*\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}